//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Platform.ServiceIportUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceIportUser.WebServiceUserSoap")]
    public interface WebServiceUserSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Add(string xmlParams, int retType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddAsync(string xmlParams, int retType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePassword(string xmlParams, int retType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePasswordAsync(string xmlParams, int retType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUserSoapChannel : M_Platform.ServiceIportUser.WebServiceUserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUserSoapClient : System.ServiceModel.ClientBase<M_Platform.ServiceIportUser.WebServiceUserSoap>, M_Platform.ServiceIportUser.WebServiceUserSoap {
        
        public WebServiceUserSoapClient() {
        }
        
        public WebServiceUserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Add(string xmlParams, int retType) {
            return base.Channel.Add(xmlParams, retType);
        }
        
        public System.Threading.Tasks.Task<string> AddAsync(string xmlParams, int retType) {
            return base.Channel.AddAsync(xmlParams, retType);
        }
        
        public string UpdatePassword(string xmlParams, int retType) {
            return base.Channel.UpdatePassword(xmlParams, retType);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePasswordAsync(string xmlParams, int retType) {
            return base.Channel.UpdatePasswordAsync(xmlParams, retType);
        }
    }
}
