//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Platform.ServiceSendMessage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSendMessage.mobileSoap")]
    public interface mobileSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 desaddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmessage", ReplyAction="*")]
        M_Platform.ServiceSendMessage.sendmessageResponse sendmessage(M_Platform.ServiceSendMessage.sendmessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmessage", ReplyAction="*")]
        System.Threading.Tasks.Task<M_Platform.ServiceSendMessage.sendmessageResponse> sendmessageAsync(M_Platform.ServiceSendMessage.sendmessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendmessage", Namespace="http://tempuri.org/", Order=0)]
        public M_Platform.ServiceSendMessage.sendmessageRequestBody Body;
        
        public sendmessageRequest() {
        }
        
        public sendmessageRequest(M_Platform.ServiceSendMessage.sendmessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendmessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string desaddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string send_user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string send_system;
        
        public sendmessageRequestBody() {
        }
        
        public sendmessageRequestBody(string desaddr, string msg, string send_user, string send_system) {
            this.desaddr = desaddr;
            this.msg = msg;
            this.send_user = send_user;
            this.send_system = send_system;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendmessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public M_Platform.ServiceSendMessage.sendmessageResponseBody Body;
        
        public sendmessageResponse() {
        }
        
        public sendmessageResponse(M_Platform.ServiceSendMessage.sendmessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendmessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendmessageResult;
        
        public sendmessageResponseBody() {
        }
        
        public sendmessageResponseBody(bool sendmessageResult) {
            this.sendmessageResult = sendmessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mobileSoapChannel : M_Platform.ServiceSendMessage.mobileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mobileSoapClient : System.ServiceModel.ClientBase<M_Platform.ServiceSendMessage.mobileSoap>, M_Platform.ServiceSendMessage.mobileSoap {
        
        public mobileSoapClient() {
        }
        
        public mobileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mobileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_Platform.ServiceSendMessage.sendmessageResponse M_Platform.ServiceSendMessage.mobileSoap.sendmessage(M_Platform.ServiceSendMessage.sendmessageRequest request) {
            return base.Channel.sendmessage(request);
        }
        
        public bool sendmessage(string desaddr, string msg, string send_user, string send_system) {
            M_Platform.ServiceSendMessage.sendmessageRequest inValue = new M_Platform.ServiceSendMessage.sendmessageRequest();
            inValue.Body = new M_Platform.ServiceSendMessage.sendmessageRequestBody();
            inValue.Body.desaddr = desaddr;
            inValue.Body.msg = msg;
            inValue.Body.send_user = send_user;
            inValue.Body.send_system = send_system;
            M_Platform.ServiceSendMessage.sendmessageResponse retVal = ((M_Platform.ServiceSendMessage.mobileSoap)(this)).sendmessage(inValue);
            return retVal.Body.sendmessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<M_Platform.ServiceSendMessage.sendmessageResponse> M_Platform.ServiceSendMessage.mobileSoap.sendmessageAsync(M_Platform.ServiceSendMessage.sendmessageRequest request) {
            return base.Channel.sendmessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<M_Platform.ServiceSendMessage.sendmessageResponse> sendmessageAsync(string desaddr, string msg, string send_user, string send_system) {
            M_Platform.ServiceSendMessage.sendmessageRequest inValue = new M_Platform.ServiceSendMessage.sendmessageRequest();
            inValue.Body = new M_Platform.ServiceSendMessage.sendmessageRequestBody();
            inValue.Body.desaddr = desaddr;
            inValue.Body.msg = msg;
            inValue.Body.send_user = send_user;
            inValue.Body.send_system = send_system;
            return ((M_Platform.ServiceSendMessage.mobileSoap)(this)).sendmessageAsync(inValue);
        }
    }
}
